import { DecisionRecord } from "./types";

export const OWNER_TAG = "owner:Elena Werning";

export const CONFIG = {
  useMockData: false,
  endpoints: {
    logs: "/api/logs",
    metrics: "/api/metrics",
    createDecision: "/api/decisions",
    feedback: "/api/feedback",
  },
  thresholds: {
    minAcceptance: 0.7,
    minFirstPass: 0.65,
    maxDriftRate: 0.3,
    maxReworkRate: 0.35,
    minSaveSuccess: 0.98,
  },
};

export const seedLogs: DecisionRecord[] = [
  {
    id: "dec_1001",
    ts: "2026-04-10 11:21:05",
    orderRef: "ORD-4102",
    predictionId: "pred_aa12",
    dbCheck: "found",
    action: "accept",
    drift: false,
    actor: "operator:lea",
    owner: OWNER_TAG,
    overrideUsed: false,
    overrideReason: "",
    reasonCode: "rule_match",
    sourceContext: "db+heuristic",
    guardrailState: "clean",
  },
  {
    id: "dec_1002",
    ts: "2026-04-10 11:25:44",
    orderRef: "ORD-4103",
    predictionId: "pred_bb90",
    dbCheck: "not_found",
    action: "hold",
    drift: true,
    actor: "operator:mika",
    owner: OWNER_TAG,
    overrideUsed: false,
    overrideReason: "",
    reasonCode: "missing_record",
    sourceContext: "manual_review",
    guardrailState: "warning",
  },
  {
    id: "dec_1003",
    ts: "2026-04-10 11:31:12",
    orderRef: "ORD-4104",
    predictionId: "pred_kq22",
    dbCheck: "found",
    action: "accept",
    drift: true,
    actor: "operator:lea",
    owner: OWNER_TAG,
    overrideUsed: true,
    overrideReason: "Owner Override wegen hoher Priorität bei sonst stabilem Datensatz.",
    reasonCode: "accepted_with_drift_review",
    sourceContext: "db+manual_override",
    guardrailState: "warning",
  },
  {
    id: "dec_1004",
    ts: "2026-04-10 11:42:09",
    orderRef: "ORD-4105",
    predictionId: "pred_xx18",
    dbCheck: "not_found",
    action: "reject",
    drift: false,
    actor: "operator:sam",
    owner: OWNER_TAG,
    overrideUsed: false,
    overrideReason: "",
    reasonCode: "policy_reject",
    sourceContext: "policy_gate",
    guardrailState: "clean",
  },
];
